language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t fracassoj/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true fracassoj/docker-react npm run test 
